LIBDPARSE=Dscanner/libdparse/src/dparse/ast.d Dscanner/libdparse/src/dparse/formatter.d Dscanner/libdparse/src/dparse/parser.d Dscanner/libdparse/src/dparse/entities.d  Dscanner/libdparse/src/dparse/lexer.d Dscanner/libdparse/src/std/experimental/lexer.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/stats_collector.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/fallback_allocator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/bucketizer.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/affix_allocator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/quantizer.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/package.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/region.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/bitmapped_block.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/segregator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/scoped_allocator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/free_tree.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/kernighan_ritchie.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/free_list.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/null_allocator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/building_blocks/allocator_list.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/typed.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/mmap_allocator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/package.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/common.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/mallocator.d ./Dscanner/libdparse/experimental_allocator/src/std/experimental/allocator/gc_allocator.d # ./Dscanner/libdparse/src/dparse/rollback_allocator.d ./Dscanner/libdparse/src/dparse/stack_buffer.d

LIBDDOC=libddoc/src/ddoc/highlight.d libddoc/src/ddoc/lexer.d libddoc/src/ddoc/package.d libddoc/src/ddoc/standalone.d libddoc/src/ddoc/sections.d libddoc/src/ddoc/macros.d libddoc/src/ddoc/comments.d
DSCANNER_COMPONENTS=Dscanner/src/outliner.d Dscanner/src/symbol_finder.d
HARBORD_COMPONENTS=harbored/src/tocbuilder.d harbored/src/unittest_preprocessor.d harbored/src/visitor.d harbored/src/macros.d
DSYMBOL_COMPONENTS=Dscanner/dsymbol/src/dsymbol/scope_.d Dscanner/dsymbol/src/dsymbol/builtin/names.d Dscanner/dsymbol/src/dsymbol/builtin/symbols.d Dscanner/dsymbol/src/dsymbol/modulecache.d Dscanner/dsymbol/src/dsymbol/import_.d Dscanner/dsymbol/src/dsymbol/string_interning.d Dscanner/dsymbol/src/dsymbol/type_lookup.d Dscanner/dsymbol/src/dsymbol/cache_entry.d Dscanner/dsymbol/src/dsymbol/semantic.d Dscanner/dsymbol/src/dsymbol/conversion/second.d Dscanner/dsymbol/src/dsymbol/conversion/package.d Dscanner/dsymbol/src/dsymbol/conversion/first.d Dscanner/dsymbol/src/dsymbol/deferred.d Dscanner/dsymbol/src/dsymbol/symbol.d Dscanner/containers/src/containers/immutablehashset.d Dscanner/containers/src/containers/package.d Dscanner/containers/src/containers/hashset.d Dscanner/containers/src/containers/treemap.d Dscanner/containers/src/containers/internal/mixins.d Dscanner/containers/src/containers/internal/storage_type.d Dscanner/containers/src/containers/internal/element_type.d Dscanner/containers/src/containers/internal/hash.d Dscanner/containers/src/containers/internal/node.d Dscanner/containers/src/containers/dynamicarray.d Dscanner/containers/src/containers/ttree.d Dscanner/containers/src/containers/simdset.d Dscanner/containers/src/containers/unrolledlist.d Dscanner/containers/src/containers/hashmap.d Dscanner/containers/src/containers/slist.d Dscanner/containers/src/containers/openhashset.d

all:
	#dmd diff.d terminal.d $(LIBDPARSE)
	dmd doc2.d comment.d stemmer.d dom.d -J. $(LIBDPARSE) -g # -debug=verbose
	#dmd -of/var/www/dpldocs.info/locate locate.d  dom stemmer.d  cgi -J. -version=fastcgi -m64 -debug
